export const GET_BLOCKCHAIN_STATE_BEGIN = "GET_BLOCKCHAIN_STATE_BEGIN";
export const GET_BLOCKCHAIN_STATE_SUCCESS = "GET_BLOCKCHAIN_STATE_SUCCESS";
export const GET_BLOCKCHAIN_STATE_FAILURE = "GET_BLOCKCHAIN_STATE_FAILURE";
