export const GET_STATE_BEGIN = "GET_STATE_BEGIN";
export const GET_STATE_SUCCESS = "GET_STATE_SUCCESS";
export const GET_STATE_FAILURE = "GET_STATE_FAILURE";
export const SET_CURRENT_STATE = "SET_CURRENT_STATE";
