export const GET_TRANSACTIONS_BEGIN = "GET_TRANSACTIONS_BEGIN";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAILURE = "GET_TRANSACTIONS_FAILURE";
export const SET_CURRENT_TRANSACTION = "SET_CURRENT_TRANSACTION";
