export const GET_TRANSACTIONS_BEGIN = "GET_TRANSACTIONS_BEGIN";
export const POST_TRANSACTIONS_BEGIN = "POST_TRANSACTIONS_BEGIN";
export const GET_TRANSACTIONS_BY_SENDER_SUCCESS = "GET_TRANSACTIONS_BY_SENDER_SUCCESS";
export const GET_TRANSACTIONS_BY_RECIPIENT_SUCCESS = "GET_TRANSACTIONS_BY_RECIPIENT_SUCCESS";
export const POST_TRANSACTIONS_SUCCESS = "POST_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAILURE = "GET_TRANSACTIONS_FAILURE";
export const POST_TRANSACTIONS_FAILURE = "POST_TRANSACTIONS_FAILURE";
export const SET_CURRENT_TRANSACTION = "SET_CURRENT_TRANSACTION";
